"""add_report_resolutions

Revision ID: 5e782caedebd
Revises: f2aa46e03e5f
Create Date: 2026-05-12 17:28:18.889464

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e782caedebd"
down_revision: Union[str, Sequence[str], None] = "f2aa46e03e5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_resolutions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("resolved_by_id", sa.UUID(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column(
            "resolved_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["report_id"], ["reports.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_id"),
    )
    op.create_table(
        "resolution_photos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("resolution_id", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resolution_id"], ["report_resolutions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "reports", sa.Column("assigned_to_id", sa.UUID(), nullable=True)
    )
    op.create_index(
        op.f("ix_reports_assigned_to_id"),
        "reports",
        ["assigned_to_id"],
        unique=False,
    )
    op.create_foreign_key(None, "reports", "users", ["assigned_to_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reports", type_="foreignkey")
    op.drop_index(op.f("ix_reports_assigned_to_id"), table_name="reports")
    op.drop_column("reports", "assigned_to_id")
    op.drop_table("resolution_photos")
    op.drop_table("report_resolutions")
    # ### end Alembic commands ###
